In [11]:
import numpy as np

In [12]:
# import parameter matrices prepared for figures in the paper
import Parameters_for_Figures

In [13]:
print(Parameters_for_Figures.D0_3a)

[[-2.020e+00  1.000e-02  1.000e-02]
 [ 1.000e-01 -7.200e+00  1.000e-01]
 [ 0.000e+00  1.000e-02 -1.601e+01]]


In [14]:
print(Parameters_for_Figures.D1_3a)

[[ 1  0  1]
 [ 1  5  1]
 [ 0  1 15]]


In [15]:
print(Parameters_for_Figures.D0_3b)

[[ -2.2   0.1   0.    0.    0.1]
 [  0.1  -2.7   0.5   0.    0.1]
 [  0.1   0.2  -5.4   0.    0.1]
 [  0.1   0.1   0.3  -3.5   0. ]
 [  0.1   0.1   0.1   0.1 -15.4]]


In [16]:
print(Parameters_for_Figures.D1_3b)

[[ 0  0  1  0  1]
 [ 1  1  0  0  0]
 [ 1  2  1  1  0]
 [ 1  0  0  1  1]
 [ 0  0  0  0 15]]


In [17]:
print(Parameters_for_Figures.D0_3c)

[[-10.07374684   0.23010913   1.6696843    0.           0.
    0.           0.           0.           0.           0.        ]
 [  0.50184725  -9.38520611   1.21813308   0.20959221   0.
    0.           0.           0.           0.           0.        ]
 [  0.81537406   0.09219164 -11.67794993   0.26678193   1.48928096
    0.           0.           0.           0.           0.        ]
 [  1.09377831   0.11073208   1.35363248 -12.43112131   0.48117924
    0.72100167   0.           0.           0.           0.        ]
 [  0.           1.59579804   1.57706975   0.08693897 -16.00748026
    0.65427811   0.71862168   0.           0.           0.        ]
 [  0.           0.           1.64080376   0.57461037   0.23284741
  -18.25475205   1.71827498   1.21847676   0.           0.        ]
 [  0.           0.           0.           0.24409973   0.90070117
    1.20773138 -12.22413338   1.33218043   0.7875591    0.        ]
 [  0.           0.           0.           0.           1.20400401
    

In [18]:
print(Parameters_for_Figures.D1_3c)

[[2.35722872 0.3451637  2.50452645 2.96703454 0.         0.
  0.         0.         0.         0.        ]
 [0.50184725 3.16356421 1.82719962 0.31438831 1.64863418 0.
  0.         0.         0.         0.        ]
 [0.81537406 0.09219164 4.6283194  0.40017289 2.23392145 0.84434191
  0.         0.         0.         0.        ]
 [1.09377831 0.11073208 1.35363248 4.07751458 0.72176886 1.08150251
  0.2318687  0.         0.         0.        ]
 [0.         1.59579804 1.57706975 0.08693897 4.72220876 0.98141717
  1.07793251 1.33340849 0.         0.        ]
 [0.         0.         1.64080376 0.57461037 0.23284741 4.59792571
  2.57741247 1.82771514 1.41842391 0.        ]
 [0.         0.         0.         0.24409973 0.90070117 1.20773138
  2.07415398 1.99827064 1.18133865 0.145566  ]
 [0.         0.         0.         0.         1.20400401 0.60782461
  0.38186133 4.12905981 1.62348664 1.22721783]
 [0.         0.         0.         0.         0.         1.05102917
  1.05279905 1.33703143 4.73

In [19]:
print(Parameters_for_Figures.D0_3d)

[[-2.34498223e+01  2.30109133e-01  1.66968430e+00  1.97802303e+00
   1.56766470e+00  2.26976944e-01  3.49805419e-02  6.01928912e-01
   9.89203291e-01  1.35146283e+00  1.64622068e+00  1.69332481e+00
   8.40365934e-01  1.86216573e-01  1.96838370e+00  1.74699286e-01
   7.30211166e-01  1.84807023e+00  6.01746660e-01  1.64893895e+00]
 [ 5.01847247e-01 -2.02030286e+01  1.21813308e+00  2.09592209e-01
   1.09908945e+00  1.26966741e+00  1.94896619e+00  1.78314653e+00
   4.94123664e-01  4.56166209e-01  8.94243644e-02  5.22359631e-02
   1.12233108e+00  7.26478994e-01  1.94331184e+00  6.66824532e-01
   4.60954199e-01  9.02411832e-01  3.15741161e-01  3.73891633e-01]
 [ 8.15374056e-01  9.21916413e-02 -2.02189215e+01  2.66781928e-01
   1.48928096e+00  5.62894604e-01  4.98086183e-01  1.45746927e+00
   5.69722335e-01  1.85267027e+00  5.10947848e-01  6.86607345e-01
   4.21541280e-01  9.09750805e-01  3.69753376e-01  9.67719961e-01
   1.34740325e+00  8.22122141e-01  9.92120698e-01  1.73383015e+00]
 [ 1.09

In [20]:
print(Parameters_for_Figures.D1_3d)

[[0.62538161 0.11505457 0.83484215 0.98901151 0.78383235 0.11348847
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.25092362 1.44504319 0.60906654 0.1047961  0.54954473 0.63483371
  0.97448309 0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.40768703 0.04609582 1.26161411 0.13339096 0.74464048 0.2814473
  0.24904309 0.72873463 0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.54688916 0.05536604 0.67681624 2.577546   0.24058962 0.36050084
  0.07728957 0.75807586 0.35146781 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.38477312 0.79789902 0.78853488 0.04346949 0.51348466 0.32713906
  0.35931084 0.4444695  0.31307694 0.70760514 0.         0.
  0.         0.      